language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler -v '1.17.3'
cache:
  bundler: true
install:
  - bundle install
script:
  - bundle exec rake test
