org_line: International Growth
director: christianblais
owners:
- Shopify/intl-languages
- Shopify/intl-localization
- Shopify/intl-eng
slack_channels:
  - intl-dev
classification: library
ci_url: https://travis-ci.org/Shopify/pseudolocalization
